server:
  port: 8889
  servlet:
    context-path: /spring-cloud-grpc-client
spring:
  application:
    name: spring-cloud-grpc-client
#  profiles:
#    active: dev
#-----------------------------------注册到注册中心[开始]--------------------------------------------------
eureka:
  instance:
    prefer-ip-address: true  #将自己的ip注册到eureka上
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/  #与注册中心交互的地址，多个逗号隔开
    #backup-registry-impl: 启动时候找不到服务，则使用该配置的自定义服务 com.example.BackupServiceRegistry
