server:
  port: 8887
  servlet:
    context-path: /spring-cloud-redis
spring:
  application:
    name: spring-cloud-redis
  profiles:
    active: dev
#-----------------------------------DAO层-mybatis-2/2[开始]-----------------------------------------------
mybatis.:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

